# Generated by Django 4.0.4 on 2022-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=5)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
